import Button from "@/components/Button/Button";
import HTag from "@/components/HTag/HTag";
import MyArrowIcon from "@/components/MyArrowIcon/MyArrowIcon";
import Paragraph from "@/components/Paragraph/Paragraph";
import Rating from "@/components/Rating/Rating";
import Tag from "@/components/Tag/Tag";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [rating, setRating] = useState(0);
  return (
    <>
      <Head>
        <title>Top app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Rating rating={rating} isEdited={true} setRating={setRating} />
    </>
  );
}
